### ISSUE TITLE
Compilation errors for Libraries flagged OK

### ISSUE THREAD

**Issue by pbrena** [fhdm-dev/pico-arduino-compat#1]
Hello,

I must be missing something basic because I get compilations errors for Libraries flagged OK on the list.

- I include a pair of messages, let me know if more is required.
- I include (working before including the new Lib)  the CMakeLists bellow
- I tried several libs involving keypads with similar results
- I was able to compile one of your working examples without problems (ssd1603?)

Thx, Pablo

MESSAGE Examples

In file included from /Volumes/HDD/TotArchiv/aAplicaciones/pico/pico-arduino-compat/libs/keypad/Keypad/src/Keypad.h:36,
                 from /Volumes/HDD/TotArchiv/aAplicaciones/pico/pico-arduino-compat/libs/keypad/Keypad/src/Keypad.cpp:32:
/Volumes/HDD/TotArchiv/aAplicaciones/pico/pico-arduino-compat/libs/keypad/Keypad/src/Key.h:51:2 error: 'boolean' does not name a type; did you mean 'bool'?
   51 |  boolean stateChanged;
      |  ^~~~~~~
      |  bool
/Volumes/HDD/TotArchiv/aAplicaciones/pico/pico-arduino-compat/libs/keypad/Keypad/src/Keypad.cpp:247:27: error: 'byte' was not declared in this scope; did you mean 'std::byte'?
  247 | void Keypad::transitionTo(byte idx, KeyState nextState) {
      |                           ^~~~
      |                           std::byte

CMakeLists:

cmake_minimum_required(VERSION 3.13)

set(CMAKE_TRY_COMPILE_TARGET_TYPE "STATIC_LIBRARY")
include(pico_sdk_import.cmake)

project(pico-superkey-board_project C CXX ASM)
set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 17)
pico_sdk_init()

add_executable(pico-superkey-board
    pico-superkey-board.cpp
    TinyUSB_Mouse_and_Keyboard/TinyUSB_Mouse_and_Keyboard.cpp
    Adafruit_TinyUSB_Arduino/src/arduino/hid/Adafruit_USBD_HID.cpp
    Adafruit_TinyUSB_Arduino/src/arduino/Adafruit_USBD_Device.cpp
    Adafruit_TinyUSB_Arduino/src/arduino/ports/rp2040/Adafruit_TinyUSB_rp2040.cpp
    Print.cpp
)

target_include_directories(pico-superkey-board PRIVATE ${CMAKE_CURRENT_LIST_DIR})

target_link_libraries(pico-superkey-board
    pico_stdlib
    pico_unique_id
    tinyusb_device
    tinyusb_board
    pac-keypad
)
pico_add_extra_outputs(pico-superkey-board)

add_definitions(-DUSE_TINYUSB)
add_definitions(-DUSB_PRODUCT="Pico Keyboard")
add_definitions(-DARDUINO_ARCH_RP2040)
add_definitions(-DCFG_TUSB_CONFIG_FILE="includes/tusb_config.h")

include_directories(includes
    /Volumes/HDD/TotArchiv/aAplicaciones/pico/pico-arduino-compat/arduino-compat/arduino-pico/cores/rp2040
    TinyUSB_Mouse_and_Keyboard
    Adafruit_TinyUSB_Arduino/src
)
add_subdirectory("/Volumes/HDD/TotArchiv/aAplicaciones/pico/pico-arduino-compat/libs/keypad"  
                  build-pac-keypad )

#remove Adafruit tinyusb library code so that only the pico-sdk tinyusb code is used
#to restore, cd Adafruit_TinyUSB_Arduino/ && git checkout HEAD .
#file(REMOVE Adafruit_TinyUSB_Arduino/src/tusb.c)
#file(REMOVE Adafruit_TinyUSB_Arduino/src/tusb.h)
#file(REMOVE Adafruit_TinyUSB_Arduino/src/tusb_option.h)
#file(REMOVE_RECURSE Adafruit_TinyUSB_Arduino/src/osal/)
#file(REMOVE_RECURSE Adafruit_TinyUSB_Arduino/src/portable/)
#file(REMOVE_RECURSE Adafruit_TinyUSB_Arduino/src/device/)
#file(REMOVE_RECURSE Adafruit_TinyUSB_Arduino/src/common/)
#file(REMOVE_RECURSE Adafruit_TinyUSB_Arduino/src/class/)

**Comment by fhdm-dev** [comment]
Hi,

Sorry but I don't know why you're getting that error message. The keypad library wasn't tested with with the adafruit tinyusb library.

My CMakeLists.txt looks like this (make also failed with this but for a different reason)


```
cmake_minimum_required(VERSION 3.12)

include(pico_sdk_import.cmake)

project(test_project)

pico_sdk_init()

add_subdirectory(../../prod/pico-arduino-compat/libs/keypad build-keypad)
add_subdirectory(../../prod/pico-arduino-compat/libs/adafruit-tinyusb-library build-adafruit-tinyusb-library)

add_definitions(-DUSE_TINYUSB)
add_definitions(-DUSB_PRODUCT="Pico Keyboard")
add_definitions(-DARDUINO_ARCH_RP2040)
add_definitions(-DCFG_TUSB_CONFIG_FILE="includes/tusb_config.h")

add_executable(test
    test.c
)

# Pull in our pico_stdlib which pulls in commonly used features
target_link_libraries(test
pico_stdlib
pac-adafruit-tinyusb-library
pac-keypad
)

# create map/bin/hex file etc.
pico_add_extra_outputs(test)`

```

**Comment by pbrena** [comment]
thx, a lot
